### ISSUE TITLE
Dynamically loaded tool-chain based command plugins

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-common#52]
We now have the script plugins to extend the `ceylon` command, it would be nice to have the same for Ceylon/legacy modules (containing classes) implementing the `Tool` interface.

**Comment by quintesse** [comment]
Ok, so this works. There is a crappy bit that I'm still going to change but I wanted to push what I had for now.

So how this works is that, just like the shell/bat files that you can add to ~/.ceylon/bin and /etc/ceylon/bin etc you can now also add a `.plugin` file which follows a similar naming scheme: `ceylon-mycommand.plugin` would add a new command named `mycommand`.

The format of the file is simply a properties file with the following contents:

```
summary=This is a test plugin
module=com.example.testplugin/1.0.0
class=CeylonTestTool
```

The `summary` is so we can type `ceylon` and get a list of all the commands (built-in and plugins) without having to actually go fetch the module and load it. (It should of course be the same as the `@Summary` annotation used in the tool class itself).

The `module` is just the module that contains the tool. The tool should be based on the `Tool` interface that all other built-in commands use.

The `class` is optional, because by default it will try for `CeylonMycommandTool` if the name of the tool is `mycommand`. If you want to use a different class name you specify it here, as long as it implements `Tool` everything will be fine.

**Comment by quintesse** [comment]
Another change that I made at the same time is to allow for "local" plugins. That means that you can install plugins in `./.ceylon/bin`, the `ceylon plugin` tool now supports this with the `--local` option. (NB: the plugin tool now also knows about the new plugins described above of course).

I also changed the *order* in which the plugins are looked up, they now go from most local to least local: local, user, system, ceylon installation and finally $PATH.
This makes it possible for example to have the `ceylon format` command installed from version 1.0.0 while working on version 1.1.0 and have it work in its project folder.

**Comment by FroMage** [comment]
Yay, this sounds great! Do we have any plugin example? Is this already integrated with `ceylon plugin` as well? We'll need Herd support too!

**Comment by quintesse** [comment]
`ceylon plugin` support is already done. I had forgotten about Herd, I'll do that ASAP

**Comment by quintesse** [comment]
Herd support implemented.

**Comment by FroMage** [comment]
Yay!

**Comment by FroMage** [comment]
This is done, right?

**Comment by quintesse** [comment]
No, not 100% yet.

**Comment by quintesse** [comment]
I'll close this now, any things I'd like to change can wait for the future.

**Comment by luolong** [comment]
@quintesse, I am looking at this discussion and one thing is bothering me.

Can't this be somehow annotation driven?

**Comment by quintesse** [comment]
@luolong well it *is* annotation-driven... mostly ;)
All the internal Ceylon tools use (Java) annotations for defining command line flags and arguments and documentation and what not.
But there's the issue of bootstrapping that, you can't read annotations from a module you haven't loaded yet, and you definitely don't want to load all the modules looking for tools.
So that's why I came up with this system where we have a simple text-based "registry" that's very quick to scan and parse so we don't slow things down with expensive module and class loading until actually needed.
