### ISSUE TITLE
Allow additional or custom backends in native annotations

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-common#62]
[This](https://github.com/ceylon/ceylon-common/pull/61) didn't make the cut, so it would be nice to find an alternate solution for 1.2.

I don't understand how `native` works well enough to offer any great ideas on this. But one observation is that it would also be nice to be able to compile using an installed backend (say, "jvm"), despite not having other backends installed that may be supported by a module.

**Comment by quintesse** [comment]
I still have this on my TODO list for 1.2 :)

**Comment by quintesse** [comment]
Would this be enough for now @jvasileff ?

**Comment by jvasileff** [comment]
Thanks a lot @quintesse! I haven't done much with `native` yet, but it certainly looks like it will be enough.

**Comment by quintesse** [comment]
Ok, then I'll close this. We can open other issues when additional requirements come up.
This is just very basic support and if someone would add a new backend they'd still have to register their backend at some point during startup, but at least it will be possible.

**Comment by jvasileff** [comment]
@quintesse thanks again. I added initial support for this in the Dart backend, and it works great.

A significant problem remains, however, that code with `native("dart")` is not compatible with the JS and JVM backends, and produces errors in Eclipse. I wonder if there is some possible short-term workaround/hack for this. Perhaps an undocumented `.ceylon/config` feature to add a backend?
